export const SET_CUSTOMER_INFO = 'SET_CUSTOMER_INFO';

export const SET_CHECKOUT_STEP = 'SET_CHECKOUT_STEP';

export const SET_PAYMENT_INFO = 'SET_PAYMENT_INFO';

export const SET_PAYMENT_METHOD = 'SET_PAYMENT_METHOD';

export const SET_STRIPE_INTENT_ID = 'SET_STRIPE_INTENT_ID';

export const SET_STRIPE_CLIENT_SECRET = 'SET_STRIPE_CLIENT_SECRET';

export const SET_LAST_ORDER = 'SET_LAST_ORDER';
