export const SET_MENU = 'SET_MENU';

export const SET_RAW_PRODUCTS = 'SET_RAW_PRODUCTS';

export const SET_ACTIVE_CTGS = 'SET_ACTIVE_CTGS';

export const SET_ACTIVE_PRICE_RANGES = 'SET_ACTIVE_PRICE_RANGES';
